### ISSUE TITLE
What about putting the whole semantic specification (f.k.a. Data Dictionary PDF) directly within the OpenAPI document?

### ISSUE THREAD

**Issue by patricekrakow** [papinet/papiNet-API#111]
Since the `description` properties do support the (full?) markdown syntax **and** since we have decided to define (almost) all the properties locally, we do have a new (compared to the XML time) to maintain the semantic specification directly within the OpenAPI document, instead of using a separate file (i.e. `papiNet-API.md`).

**Comment by patricekrakow** [comment]
Let's have a try, I can transfer the current content of `papiNet-API.md` within the `papiNet-API.yaml`. We also need to update the _papiNet JSON Style Guide_, adding the rule that we should not add a `description` to the self-explanatory properties or values, e.g. meter.

**Comment by patricekrakow** [comment]
Here is an example:

```yaml
purchaseOrderNumber:
  type: string
  minLength: 1
  description: |
    This is the identifier of the _purchase order_ as assigned by the _customer_.
```
