### ISSUE TITLE
Add `safetyAndEnvironmentDetails[]` to `LogisticsDeliveryNoteById.lineItems[]`, and `DeliveryInstructionById.sequences[].lineItems[]`

### ISSUE THREAD

**Issue by patricekrakow** [papinet/papiNet-API#153]
In XML, the element is called `SafetyAndEnvironmentalInformation` (XML). It's a bit annoying as (1) we want to have it as an array, and (2) there is no plural form of "information" in English. A way - to be discussed/approved later - to fix this is to add the suffix `(...)Details`. We will then use `safetyAndEnvironmentalInformationDetails` (JSON).

We will not JSON-ify the complete structure of the XML element `SafetyAndEnvironmentalInformation`, but only select the following parts:

* `SafetyAndEnvironmentalType [attribute]` (XML) will be used as `type` (JSON) with the same enumeration list:
  * Agricultural
  * Biodegradable
  * CarbonFootprint
  * Certified
  * ...

* `Agency [attribute]` (XML) will be used as `assignedBy` (JSON) with the same enumeration list:
  * AFPA
  * ...

***WARNING***: This list probably needs to be restricted dependending of the context, i.e. `safetyAndEnvironmentalInformationDetails`.

* `ChainOfCustody` (XML) and `CertificationBody [attribute]` (XML) will be used as `chainOfCustody.value` (JSON) and `chainOfCustody.assignedBy` (JSON).

The complete structure will look like the following:

```json
{
  "safetyAndEnvironmentalInformationDetails": [
    {
      "type": "FSCMixCredit",
      "assignedBy": "FSC",
      "chainOfCustody": {
        "value": "INS-COC-100054"
        "assignedBy": "..."
      }
    },
    { }
  ]
}
```

**Comment by patricekrakow** [comment]
Done, see commit [a3218cf](https://github.com/papinet/papiNet-API/commit/a3218cfe5af5178ddc3ad4e65d840a33926a9b69).

**Comment by patricekrakow** [comment]
I missed the Lars' proposal for the JSON-ification of `SafetyAndEnvironmentalInformation` (XML).

Here it is: (from email sent on Wed, Jun 26, 8:20 PM)

```yaml
safetyAndEnvironmental:
  type: object
  required:
    - type
    - assignedBy
  properties:
    # quantity and freeText existing in XML not added
    # certification now limited to a percentage, in XML a measurement value.
    type: 
      type: string
      enum:
        - Deforestation
        - FSC100%
        - FSCControlledWood
        - FSCMix_x%
        - FSCMixCredit
        - FSCRecycled_x%
        - FSCRecycledCredit
        - PEFCControlledSources
        - X%_PEFCcertified
    assignedBy:
        type: string
        enum:
          - EU
          - FSC
          - PEFC
    licenceNumber:
      type: string
      minLength: 1
    chainOfCustoty:
      type: object
      required: value
      properties:
        certificationBody:
          type: string
          minlength: 1
        value:
          type: string
          minlength: 1
    certificationPercentage:
      type: Number
      exclusiveMinimum: 0
    references:
      type: array
      minItems: 1
      items:
        type: object
        required: 
          - identifier
        properties:
          identifier:
            type: object
            required:
              - type
              - value
            properties:
              type:
                type: string
                enum:
                  - EUDRDueDiligenceStatementReferenceNumber
              value:
                type: string
                minlength: 1
          subReference:
            type: object
            required: 
              - identifier
            identifier:
              type: object
              required:
                - type
                - value
              properties:
                type:
                  type: string
                  enum:
                    - EUDRDueDiligenceStatementVerificationNumber
                value:
                  type: string
                  minlength: 1
```

(I have just corrected a little indentation issue).
