### ISSUE TITLE
Missing `classification` within `sellerProduct`

### ISSUE THREAD

**Issue by patricekrakow** [papinet/papiNet-API#154]
We agreed (2024-06-19) on this simple structure

```yaml
classification:
  type: object
  properties:
    type:
      type: string
      enum:
        - ExportHarmonisedSystemCode
        - ... # re-use `ClassificationCodeType [attribute]` enumeration
    value:
      type: string
      minLength: 1
```
