### ISSUE TITLE
Missing `loadingCharacteristics[]` and `unloadingCharacteristics[]` within `LogisticsDeliveryNoteById.lineItems[]` and `DeliveryInstructionById.sequences[].lineItems[]`

### ISSUE THREAD

**Issue by patricekrakow** [papinet/papiNet-API#156]
We agreed (2024-06-19) on this structure:

```yaml
loadingCharacteristics:
  type: array
  minItems: 1
  items:
    type: object
    required: []
      # type is not required
      # code is not required
      # labelOrientation is not required
      # text is not required
    properties:
      type:
        type: string
        enum:
          - ByLoadingCode
          - Lying
          - Standing
          - StandingUpsideDown
          - Other
      code:
        type: object
        required:
          - value
          - assignedBy
        properties:
          value:
            type: string
            minLength: 1
          assignedBy:
            type: string
            enum:
              -Supplier
      labelOrientation:
        type: string
        enum:
          - BackEndSide
          - FrontEndSide
          - LeftAndRightSide
          - LeftSide
          - RightSide
      text:
        type: string
        minLength: 1
```
