### ISSUE TITLE
Properties status and shipmentStatus for delivery notes, version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#186]
1. Enumeration **Cancelled** exists both in properties status and shipmentStatus in ListOfLogisticsDeliveryNotes and LogisticsDeliveryNoteById. It is confusing.
I propose that **Cancelled** should be removed from shipmentStatus.

2. If the supplier (server) change the shipmentStatus to Arrived or Unloaded when receiving a logistics goods receipt, would then status be set to Replaced? Handling of status and shipmentStatus is confusing especially without any documentation.
For example: When requesting a logistics delivery note the status is Original. When later requesting the same logistics delivery note, the status should be Replaced if something has changed.
Should Arrived and Unloaded be removed from shipmentStatus?
```
             status:
                type: string
                enum:
                  - Cancelled
                  - Original
                  - Replaced
              shipmentStatus:
                type : string
                enum:
                  - Arrived
                  - Cancelled
                  - Departed
                  - Loaded
                  - Planned
                  - Unloaded
```
