### ISSUE TITLE
Properties paperAndBoard and pulp in sellerProduct, version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#188]
Properties paperAndBoard and pulp in sellerProduct are specified as required in the schema in an oneOf construct.

These properties might not be needed when sellerProduct is a fully specified product.
I propose that properties paperAndBoard and pulp in sellerProduct should be changed to optional.

**Comment by patricekrakow** [comment]
We have 4 occurrences of `sellerProduct` with the following structure:

```yaml
allOf:
  - oneOf:
      - required:
          - gradeCode
      - required:
          - partNumber
  - oneOf:
      - required:
          - paperAndBoard
      - required:
          - pulp
```

We can simplify it with:

```yaml
oneOf:
  - required:
      - gradeCode
  - required:
      - partNumber
```

**Comment by patricekrakow** [comment]
We need to have another construct because we can't have `paperAndBoard` and `pulp` at the same time. Using `dependencies` keywork of JSON schema seems usable, e.g.

```json
"dependencies": {
  "field_2": { "not": { "required": [ "field_3" ] } },
  "field_3": { "not": { "required": [ "field_2" ] } }
}
```

**Comment by patricekrakow** [comment]
The construct above does not work: 'not being required' does not mean that 'it can't be there'... I need help!

**Comment by patricekrakow** [comment]
The following construct seems to work:

```yaml
type: object
unevaluatedProperties: false
required:
  - sellerProduct
properties:
  sellerProduct:
    type: object
    unevaluatedProperties: false
    properties:
      gradeCode:
        type: string
      partNumber:
        type: string
      paperAndBoard:
        type: object
      pulp:
        type: object
    allOf:
      - not:
          required:
            - gradeCode
            - partNumber
      - anyOf:
          - required:
              - gradeCode
          - required:
              - partNumber
      - not:
          required:
            - paperAndBoard
            - pulp
      - anyOf:
          - required:
              - paperAndBoard
          - required:
              - pulp
          - required: []
```

Let's check that it contains all the constraints we need, before implementing it in the schemas...

**Comment by larsolofsson** [comment]
I think the following will work.
```
               allOf:
                  - oneOf:
                      - required:
                          - gradeCode
                      - required:
                          - partNumber
                  - anyOf:
                     - oneOf:
                        - required:
                           - paperAndBoard
                        - required:
                           - pulp
                     - not:
                        - required:
                           - paperAndBoard
                        - required:
                           - pulp 
```
gradeCode and partNumber are the same as existing in current schema.

paperAndBoard and pulp are optional but both can not exist at the same time.
It is specified by an anyOf construct

- If neither are there, then the not subschema will pass, and the anyOf passes.
- If one is there, then the oneOf subschema will pass, and the anyOf passes.
- If both are there, then
      both of the oneOf subschemas will pass, so the oneOf fails
      the not subschema will fail
      so the anyOf fails

**Comment by patricekrakow** [comment]
We need to test the different options, I will prepare test cases...

**Comment by patricekrakow** [comment]
## Valid instances

```json
{
  "sellerProduct": {
    "gradeCode": "string"
  }
}
```
```json
{
  "sellerProduct": {
    "gradeCode": "string",
    "paperAndBoard": {}
  }
}
```
```json
{
  "sellerProduct": {
    "gradeCode": "string",
    "pulp": {}
  }
}
```
```json
{
  "sellerProduct": {
    "partNumber": "string"
  }
}
```
```json
{
  "sellerProduct": {
    "partNumber": "string",
    "paperAndBoard": {}
  }
}
```
```json
{
  "sellerProduct": {
    "partNumber": "string",
    "pulp": {}
  }
}
```

## Invalid instances

```json
{
  "sellerProduct": {}
}
```
```json
{
  "sellerProduct": {
    "gradeCode": "string",
    "partNumber": "string"
  }
}
```
```json
{
  "sellerProduct": {
    "gradeCode": "string",
    "partNumber": "string",
    "paperAndBoard": {}
  }
}
```
```json
{
  "sellerProduct": {
    "gradeCode": "string",
    "partNumber": "string",
    "pulp": {}
  }
}
```
```json
{
  "sellerProduct": {
    "gradeCode": "string",
    "partNumber": "string",
    "paperAndBoard": {},
    "pulp": {}
  }
}
```
```json
{
  "sellerProduct": {
    "gradeCode": "string",
    "paperAndBoard": {},
    "pulp": {}
  }
}
```

**Comment by patricekrakow** [comment]
The following construct is working:

```yaml
type: object
unevaluatedProperties: false
required:
  - sellerProduct
properties:
  sellerProduct:
    type: object
    unevaluatedProperties: false
    properties:
      gradeCode:
        type: string
      partNumber:
        type: string
      paperAndBoard:
        type: object
      pulp:
        type: object
    allOf:
      - oneOf:
          - required:
              - gradeCode
          - required:
              - partNumber
      - anyOf:
          - oneOf:
            - required:
                - paperAndBoard
            - required:
                - pulp
          - not:
              required:
                - paperAndBoard
                - pulp
```

**Comment by patricekrakow** [comment]
Let's replace:

```yaml
allOf:
  - oneOf:
      - required:
          - gradeCode
      - required:
          - partNumber
  - oneOf:
      - required:
          - paperAndBoard
      - required:
          - pulp
```

by:

```yaml
allOf:
  - oneOf:
      - required:
          - gradeCode
      - required:
          - partNumber
  - anyOf:
      - oneOf:
        - required:
            - paperAndBoard
        - required:
            - pulp
      - not:
          required:
            - paperAndBoard
            - pulp
```
