### ISSUE TITLE
Paper properties colourDescriptions: and recycled: in version 2.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#97]
Why are Paper properties colourDescriptions: and recycled: in version 2.0.0 defined as arrays?
Is it an error?
All other Paper properties are defined as single values.

       colourDescriptions:
          type: array
          minItems: 1
          items:
            type: string
            minLength: 1
        recycled:
          type: array
          minItems: 1
          items:
            type: object
            required:
              - value
              - UOM
            properties:
              value:
                type: number
              UOM:
                type: string
                enum:
                  - Percentage

**Comment by patricekrakow** [comment]
This looks like a mistake, even before from when we move out of multiple-values-property for the 2.0.0, `colourDescription` (singular) was missing, as well as for `recycled`.
```yaml
colourDescription:
  type: string
  minLength: 1
recycled:
  type: object
  required:
    - value
    - UOM
  properties:
    value:
      type: number
    UOM:
      type: string
      enum:
        - Percentage
```

**Comment by patricekrakow** [comment]
It is also weird/annoying that the `recycled` property is not a noun, maybe it is the right time to change it to something like `recycledContent`, so we can have a clear singular and plural forms that can be used in the future. Let's discuss the best name:
- OPTION 1: `recycledContent`
- OPTION 2: `recycledProprotion`
- ...

**Comment by patricekrakow** [comment]
We decided to go with:

```
colourDescription:
  type: string
  minLength: 1
recycledContent:
  type: object
  required:
    - value
    - UOM
  properties:
    value:
      type: number
    UOM:
      type: string
      enum:
        - Percentage
```
